# Generated by Django 3.0.2 on 2020-02-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
