# Generated by Django 3.0.2 on 2020-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notification',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
