# Generated by Django 3.0.2 on 2020-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='examName',
            field=models.CharField(max_length=20),
        ),
    ]
