# Generated by Django 3.0.2 on 2020-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='clgLink',
            field=models.CharField(default='https://google.com', max_length=100),
            preserve_default=False,
        ),
    ]
